### PR TITLE
fix: debug test does not output to REPL

### LINKED ISSUE #114: debugging with delve doesn't output anything to console
There is no console output displaying at the repl, not when running `require('dap-go').debug_test()` nor when running a normal main function with `Delve: debug`.

Here is a video showcasing the problem:

https://github.com/user-attachments/assets/8e1ace69-290b-4564-923e-5326038cc9b6

### PR DESCRIPTION
**Pull request by CruelAddict**
Recent changes in nvim-dap behavior required setting `outputMode = "remote"` in debug configs for stdout to be visible in REPL (see https://github.com/leoluz/nvim-dap-go/issues/108 for more info). The problem is now fixed for test scenarios too.

`test_debug` now accepts a `custom_config` argument as a way for users to get around similar problems.

fix #114

### CODE REVIEW

**Comment by lkingland** [comment]
Tested and output is now appearing by default in the repl.

@leoluz this seems to be gtg 👍🏻

**Comment by leoluz** [comment]
Thank you for your contribution.
The new outputMode was already introduced in the plugin by the following PR: https://github.com/leoluz/nvim-dap-go/pull/109
Closing this for now. Please feel free to reopen the PR if you think the issue persists.

**Comment by leoluz** [comment]
Sorry.. I misunderstood your PR. Will review it soon.

File: lua/dap-go.lua [hunk 1]
```diff
@@ -213,7 +215,7 @@ local function debug_test(testname, testpath, build_flags, extra_args)
   dap.run(config)
 end
 
-function M.debug_test()
+function M.debug_test(custom_config)
```
Comment (leoluz) [inline lua/dap-go.lua:218]: Adding the custom_config makes it more flexible for supporting future nvim_dap changes. However we need to update the docs to clarify how this works. Please consider updating the `doc/nvim-dap-go.txt` documenting its usage.

**Review by leoluz — CHANGES_REQUESTED** [review]
Tested locally and it works as expected.
Thank you for your contribution.

File: lua/dap-go.lua (hunk 1 above)
Comment (CruelAddict) [reply lua/dap-go.lua:218]: Updated documentation

**Review by leoluz — APPROVED** [review]
LGTM
thank you!
